### ISSUE TITLE
Composer VCS issue

### ISSUE THREAD

**Issue by cdbessig** [Genaker/Magento2_Payment_Bot_Block#1]
Am I doing something wrong, or is this repo not able to be added to composer with vcs since the composer.json isn't actually in the root of the repo?

`"repositories": {
        "amasty": {
            "type": "composer",
            "url": "https://composer.amasty.com/community/"
        },
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "1": {
            "type": "composer",
            "url": "https://packages.shipperhq.com"
        },
        "2": {
            "type": "vcs",
            "url": "git@github.com:Genaker/Magento2_Payment_Bot_Block.git"
        }
    },`

**Comment by Genaker** [comment]
it doesn't have composer support. If you need this feature I can make it
works for you. Also, this extension requires Redis PHP native extension to
be installed..

**Comment by Genaker** [comment]
I'm recommending install it by copy into the APP/code folder

**Comment by cdbessig** [comment]
Thanks...I found the redis dependecny the hard way on dev...submitted a pull request to update the readme with that dependency a few minutes ago.  Thans for the module - looks like it will work well for our test cases.  Will deploy Monday into a production site.

**Comment by Genaker** [comment]
Great, thanks for the update. We are using it on production also.
