### ISSUE TITLE
Attack with multiple cart IDs

### ISSUE THREAD

**Issue by VivekShingala** [Genaker/Magento2_Payment_Bot_Block#4]
Hi @Genaker 

We are attacked with different cart IDs and not the same cart ID used multiple times. It is like a script is running and adding product to the cart and visit the API.

Will it be fixed by this plugin? Also, doesn it support Magento version 2.3.5-p2

**Comment by Genaker** [comment]
It supports any Magento version. Also, It blocks also requests from the same IP address. Also, you can add your own rules, logic.

**Comment by VivekShingala** [comment]
Thank you
